from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import func
from app.database import get_db
from app.models import Transaction, CategoryRule, Budget, Alert, User
from app.api.deps import get_current_user
from app.services.budget_service import BudgetService
from app.services.alert_service import AlertService
from app.schemas.user import CategoryRuleCreate 

router = APIRouter(tags=["Intelligence Engine"])

# --- 1. INTELLIGENCE ENGINE: Create Categorization Rules ---
@router.post("/rules", status_code=status.HTTP_201_CREATED)
def create_category_rule(
    rule_in: CategoryRuleCreate, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Maps user-defined patterns to specific spending categories."""
    new_rule = CategoryRule(
        user_id=current_user.id,
        pattern=rule_in.pattern,
        category=rule_in.category,
        match_type=rule_in.match_type
    )
    try:
        db.add(new_rule)
        db.commit()
        db.refresh(new_rule)
        return {"message": "Intelligence Engine rule created", "rule_id": new_rule.id}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Database error: {str(e)}")

# --- 2. BUDGET ENGINE: Set Spending Limits ---
@router.post("/budgets", status_code=status.HTTP_201_CREATED)
def set_budget(
    budget_data: dict, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Establishes a monthly threshold for a category."""
    try:
        new_budget = Budget(
            user_id=current_user.id,
            category=budget_data.get("category"),
            monthly_limit=budget_data.get("monthly_limit"),
            month=budget_data.get("month"),
            year=budget_data.get("year")
        )
        db.add(new_budget)
        db.commit()
        db.refresh(new_budget)
        return {"message": "Budget limit established", "budget_id": new_budget.id}
    except Exception:
        db.rollback()
        raise HTTPException(status_code=400, detail="Invalid budget data provided")

# --- 3. ANALYTICS: Monthly Spending Summary ---
@router.get("/spending-summary")
def get_spending_report(
    month: int, 
    year: int, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Aggregates total spending per category using SQL aggregation."""
    report = db.query(
        Transaction.category,
        func.sum(Transaction.amount).label("total")
    ).filter(
        Transaction.user_id == current_user.id,
        Transaction.transaction_type == 'debit',
        func.extract('month', Transaction.transaction_date) == month,
        func.extract('year', Transaction.transaction_date) == year
    ).group_by(Transaction.category).all()

    return [{"category": r.category, "total": float(r.total) if r.total else 0.0} for r in report]

# --- 4. ALERT NOTIFICATIONS ---
@router.get("/alerts")
def get_alerts(
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Lists all automated notifications generated by the Budget Engine."""
    return db.query(Alert).filter(Alert.user_id == current_user.id).all()